### ISSUE TITLE
Remove internal stacktrace

### ISSUE THREAD

**Issue by unional** [unional/assertron#91]
When reporting errors, the stack trace should not highlight the lines inside `assertron`:

```sh

    InvalidOrder: Expecting 'is(2)', 'once(2)', 'any([2])', but received 'any([3, 4])'
      74 |     const index = steps.indexOf(this.state.step)
      75 |     if (index === -1)    
    > 76 |       throw new InvalidOrder(this.state.get(), 'any', steps)
      77 |      78 |     this.state.move()
      79 |     return steps[index]

      at AssertOrder.Object.<anonymous>.AssertOrder.any (../assertron/src/AssertOrder.ts:76:13)
      at src/function/function.spec.ts:79:15
      at Object.on (src/specInternal.ts:172:9)
      at Object.<anonymous> (src/function/function.spec.ts:78:13)      at step (src/function/function.spec.ts:32:23)
      at Object.next (src/function/function.spec.ts:13:51)
      at fulfilled (src/function/function.spec.ts:4:56)
```

**Comment by unional** [comment]
Can follow how Chai does it:
https://lucasfcosta.com/2017/02/17/JavaScript-Errors-and-Stack-Traces.html

**Comment by unional** [comment]
Close by #118
